import { CircleCheck, CircleDashed, Clock, Mail, PhoneCall, Ship, Sparkles, Truck, Upload, type LucideIcon } from "lucide-react";
import { completeAction } from "@/app/actions";
import { cn } from "@/lib/utils";
import { SubmitButton } from "./client-controls";
import { DEMO_NOW, formatDuration, formatTime, zoneName } from "@/lib/clock";
import { delayNote, etaText, type DelayNote as DelayNoteData } from "@/lib/eta-display";
import type { EtaPrediction, NextAction, RiskAssessment } from "@/ai/types";
import type { Confidence, Leg, NormalizedStatus, Reliability } from "@/domain/types";

type Tone = "neutral" | "blue" | "amber" | "red" | "green" | "violet";

const TONES: Record<Tone, string> = {
  neutral: "bg-slate-100 text-slate-700 ring-slate-500/15",
  blue: "bg-sky-50 text-sky-800 ring-sky-600/20",
  amber: "bg-amber-50 text-amber-800 ring-amber-600/25",
  red: "bg-red-50 text-red-700 ring-red-600/20",
  green: "bg-emerald-50 text-emerald-800 ring-emerald-600/20",
  violet: "bg-violet-50 text-violet-800 ring-violet-600/20",
};

export function Pill({ tone = "neutral", className, children, title }: { tone?: Tone; className?: string; children: React.ReactNode; title?: string }) {
  return (
    <span title={title} className={cn("inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium whitespace-nowrap ring-1 ring-inset [&>svg]:size-3", TONES[tone], className)}>
      {children}
    </span>
  );
}

export const STATUS: Record<NormalizedStatus, { label: string; tone: Tone }> = {
  booked: { label: "Booked", tone: "neutral" },
  picked_up: { label: "Picked up", tone: "blue" },
  in_transit: { label: "In transit", tone: "blue" },
  at_port: { label: "At port", tone: "blue" },
  on_vessel: { label: "At sea", tone: "blue" },
  customs_hold: { label: "Held at customs", tone: "red" },
  customs_cleared: { label: "Customs cleared", tone: "blue" },
  out_for_delivery: { label: "Out for delivery", tone: "violet" },
  delivered: { label: "Delivered", tone: "green" },
  exception: { label: "Incident", tone: "red" },
  unknown: { label: "Unrecognised update", tone: "amber" },
};

export const StatusBadge = ({ status }: { status: NormalizedStatus }) => <Pill tone={STATUS[status].tone}>{STATUS[status].label}</Pill>;

export const StaleBadge = ({ hours }: { hours: number }) => (
  <Pill tone="amber" title="The operator has not reported for longer than expected for this mode">
    <Clock /> No update for {formatDuration(hours)}
  </Pill>
);

/** Confirmed = reported by the operator. Estimated = computed by us. Always shown, never implied. */
export function ReliabilityBadge({ reliability }: { reliability: Reliability }) {
  return reliability === "confirmed" ? (
    <Pill tone="green" title="Reported by the operator">
      <CircleCheck /> Confirmed
    </Pill>
  ) : (
    <Pill tone="neutral" className="border border-dashed border-slate-400 bg-transparent ring-0" title="Estimated by us, not reported by the operator">
      <CircleDashed /> Estimated
    </Pill>
  );
}

export function ConfidenceMeter({ confidence }: { confidence: Confidence }) {
  const filled = { high: 3, medium: 2, low: 1 }[confidence];
  const color = { high: "bg-emerald-500", medium: "bg-amber-500", low: "bg-red-500" }[confidence];
  return (
    <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground" title="How sure the estimate is">
      <span className="flex gap-0.5">
        {[0, 1, 2].map((i) => (
          <span key={i} className={cn("h-2.5 w-1 rounded-full", i < filled ? color : "bg-slate-200")} />
        ))}
      </span>
      {confidence[0].toUpperCase() + confidence.slice(1)} confidence
    </span>
  );
}

export function RiskBadge({ risk }: { risk: RiskAssessment }) {
  const tone: Tone = { high: "red", medium: "amber", low: "green" }[risk.level] as Tone;
  return (
    <Pill tone={tone} className="tabular-nums" title={risk.reasons.join(" ") || "No risk factors"}>
      {risk.score} · {risk.level}
    </Pill>
  );
}

export const AiTag = ({ label = "AI" }: { label?: string }) => (
  <Pill tone="violet" title="Generated by the AI assistant">
    <Sparkles /> {label}
  </Pill>
);

const DELAY_NOTE_STYLE: Record<DelayNoteData["kind"], { className: string; title?: string }> = {
  late: { className: "font-medium text-red-700" },
  unconfirmed: { className: "font-medium text-amber-700", title: "No recent operator update, so we can't confirm it is on time" },
  on_time: { className: "text-emerald-700" },
};

export function DelayNote({ eta, stale = false }: { eta: EtaPrediction; stale?: boolean }) {
  const note = delayNote(eta, stale);
  const style = DELAY_NOTE_STYLE[note.kind];
  return (
    <span className={cn("text-xs", style.className)} title={style.title}>
      {note.text}
    </span>
  );
}

export function EtaCell({ eta, delivered, stale }: { eta: EtaPrediction; delivered: boolean; stale?: boolean }) {
  const t = etaText(eta, delivered);
  return (
    <div className="space-y-1">
      <div className="font-medium">{t.main}</div>
      <div className="flex flex-wrap items-center gap-1.5">
        <ReliabilityBadge reliability={eta.reliability} />
        {!delivered && <DelayNote eta={eta} stale={stale} />}
      </div>
    </div>
  );
}

export const MODE_ICON = { road: Truck, sea: Ship } satisfies Record<Leg["mode"], LucideIcon>;

export function ModeTrail({ legs }: { legs: Leg[] }) {
  return (
    <span className="inline-flex items-center gap-1 text-muted-foreground" aria-label={legs.map((l) => l.mode).join(" then ")}>
      {legs.map((l) => {
        const Icon = MODE_ICON[l.mode];
        return <Icon key={l.id} className="size-3.5" />;
      })}
    </span>
  );
}

export const ACTION_ICON: Record<NextAction["kind"], LucideIcon> = {
  notify_customer: Mail,
  contact_operator: PhoneCall,
  upload_document: Upload,
  none: CircleCheck,
};

const ACTION_BUTTON: Record<NextAction["kind"], { cta: string; pending: string; done: string }> = {
  notify_customer: { cta: "Send notice", pending: "Sending…", done: "Notice sent" },
  contact_operator: { cta: "Send request", pending: "Sending…", done: "Request sent" },
  upload_document: { cta: "Upload", pending: "Uploading…", done: "Uploaded" },
  none: { cta: "", pending: "", done: "" },
};

/** One click to carry out the proposed action, or proof that it was done. Demo: nothing leaves the app. */
export function ActionControl({ shipmentId, action, done, compact = false }: { shipmentId: string; action: NextAction; done: boolean; compact?: boolean }) {
  if (action.kind === "none") return null;
  const b = ACTION_BUTTON[action.kind];
  if (done) {
    return (
      <Pill tone="green" title="Demo: recorded here, nothing is sent outside the app">
        <CircleCheck /> {b.done} · {formatTime(DEMO_NOW.toISOString())} {zoneName()}
      </Pill>
    );
  }
  return (
    <form action={completeAction}>
      <input type="hidden" name="shipmentId" value={shipmentId} />
      <input type="hidden" name="kind" value={action.kind} />
      <SubmitButton
        pendingText={b.pending}
        className={cn("border border-violet-300 bg-white text-violet-800 hover:bg-violet-100", compact && "h-7 px-2 text-xs")}
      >
        {b.cta}
      </SubmitButton>
    </form>
  );
}
