import { CircleCheck, CircleDashed, Clock, Mail, PhoneCall, Ship, Sparkles, Truck, Upload, type LucideIcon } from "lucide-react";
import { completeAction } from "@/app/actions";
import { cn } from "@/lib/utils";
import { SubmitButton } from "./client-controls";
import { formatAgo, formatDuration, hoursBetween } from "@/lib/clock";
import { delayNote, etaText, type DelayNote as DelayNoteData } from "@/lib/eta-display";
import { journeyOf, type LegProgress } from "@/lib/journey";
import type { EtaPrediction, NextAction, RiskAssessment } from "@/ai/types";
import type { Confidence, Leg, NormalizedStatus, Reliability, TrackedShipment } from "@/domain/types";

type Tone = "neutral" | "moving" | "amber" | "red" | "green" | "violet";

const TONES: Record<Tone, string> = {
  neutral: "bg-muted text-foreground ring-foreground/10",
  moving: "bg-primary/5 text-primary ring-primary/20", // movement is normal: brand ink, no signal colour
  amber: "bg-amber-50 text-amber-800 ring-amber-600/25",
  red: "bg-red-50 text-red-700 ring-red-600/20",
  green: "bg-emerald-50 text-emerald-800 ring-emerald-600/20",
  violet: "bg-violet-50 text-violet-800 ring-violet-600/20",
};

export function Pill({
  tone = "neutral",
  className,
  children,
  title,
}: {
  tone?: Tone;
  className?: string;
  children: React.ReactNode;
  title?: string;
}) {
  return (
    <span
      title={title}
      className={cn(
        "inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium whitespace-nowrap ring-1 ring-inset [&>svg]:size-3",
        TONES[tone],
        className,
      )}
    >
      {children}
    </span>
  );
}

export const STATUS: Record<NormalizedStatus, { label: string; tone: Tone }> = {
  booked: { label: "Booked", tone: "neutral" },
  picked_up: { label: "Picked up", tone: "moving" },
  in_transit: { label: "In transit", tone: "moving" },
  at_port: { label: "At port", tone: "moving" },
  on_vessel: { label: "At sea", tone: "moving" },
  customs_hold: { label: "Held at customs", tone: "red" },
  customs_cleared: { label: "Customs cleared", tone: "moving" },
  out_for_delivery: { label: "Out for delivery", tone: "moving" },
  delivered: { label: "Delivered", tone: "green" },
  exception: { label: "Incident", tone: "red" },
  unknown: { label: "Unrecognised update", tone: "amber" },
};

export const StatusBadge = ({ status }: { status: NormalizedStatus }) => <Pill tone={STATUS[status].tone}>{STATUS[status].label}</Pill>;

export const StaleBadge = ({ hours }: { hours: number }) => (
  <Pill tone="amber" title="The operator has not reported for longer than expected for this mode">
    <Clock /> No update for {formatDuration(hours)}
  </Pill>
);

/** Confirmed = reported by the operator. Estimated = computed by us. Always shown, never implied. */
export function ReliabilityBadge({ reliability }: { reliability: Reliability }) {
  return reliability === "confirmed" ? (
    <Pill tone="neutral" className="bg-card ring-foreground/40" title="Reported by the operator">
      <CircleCheck /> Confirmed
    </Pill>
  ) : (
    <Pill
      tone="neutral"
      className="border border-dashed border-muted-foreground bg-transparent ring-0"
      title="Estimated by us, not reported by the operator"
    >
      <CircleDashed /> Estimated
    </Pill>
  );
}

/** Monochrome on purpose: the fill count and the word carry the level, so "low" never reads as "late". */
export function ConfidenceMeter({ confidence }: { confidence: Confidence }) {
  const filled = { high: 3, medium: 2, low: 1 }[confidence];
  return (
    <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground" title="How sure the estimate is">
      <span className="flex gap-0.5">
        {[0, 1, 2].map((i) => (
          <span key={i} className={cn("h-2.5 w-1 rounded-full", i < filled ? "bg-foreground" : "bg-border")} />
        ))}
      </span>
      {confidence[0].toUpperCase() + confidence.slice(1)} confidence
    </span>
  );
}

export function RiskBadge({ risk }: { risk: RiskAssessment }) {
  const tone: Tone = { high: "red", medium: "amber", low: "green" }[risk.level] as Tone;
  return (
    <Pill tone={tone} className="tabular-nums" title={risk.reasons.join(" ") || "No risk factors"}>
      {risk.score} · {risk.level}
    </Pill>
  );
}

export const AiTag = ({ label = "AI" }: { label?: string }) => (
  <Pill tone="violet" title="Generated by the AI assistant">
    <Sparkles /> {label}
  </Pill>
);

const DELAY_NOTE_STYLE: Record<DelayNoteData["kind"], { className: string; title?: string }> = {
  late: { className: "font-medium text-red-700" },
  unconfirmed: { className: "font-medium text-amber-700", title: "No recent operator update, so we can't confirm it is on time" },
  on_time: { className: "text-emerald-700" },
};

export function DelayNote({ eta, stale = false }: { eta: EtaPrediction; stale?: boolean }) {
  const note = delayNote(eta, stale);
  const style = DELAY_NOTE_STYLE[note.kind];
  return (
    <span className={cn("text-xs", style.className)} title={style.title}>
      {note.text}
    </span>
  );
}

export function EtaCell({ eta, delivered, stale }: { eta: EtaPrediction; delivered: boolean; stale?: boolean }) {
  const t = etaText(eta, delivered);
  return (
    <div className="space-y-1">
      <div className="font-medium">{t.main}</div>
      <div className="flex flex-wrap items-center gap-1.5">
        <ReliabilityBadge reliability={eta.reliability} />
        {!delivered && <DelayNote eta={eta} stale={stale} />}
      </div>
    </div>
  );
}

export const MODE_ICON = { road: Truck, sea: Ship } satisfies Record<Leg["mode"], LucideIcon>;

const MODE_NAME: Record<Leg["mode"], string> = { road: "Road", sea: "Sea" };
const PROGRESS_TEXT: Record<LegProgress, string> = { done: "done", current: "in progress", ahead: "planned" };

type JourneySize = "compact" | "card" | "full";

/** Last reported position: a teal dot; held or incident: a red square; stale: a hollow amber ring. */
function JourneyMarker({ status, stale, size }: { status: NormalizedStatus; stale: boolean; size: JourneySize }) {
  const alert = status === "customs_hold" || status === "exception";
  return (
    <span
      className={cn(
        "shrink-0 ring-2 ring-card",
        size === "compact" ? "size-2.5" : "size-3.5",
        alert ? "rounded-[2px] bg-red-600" : stale ? "rounded-full border-2 border-amber-600 bg-card" : "rounded-full bg-route",
      )}
    />
  );
}

const Stretch = ({ solid }: { solid: boolean }) => (
  <span className={cn("h-0 min-w-2 flex-1 border-t-2", solid ? "border-route" : "border-dashed border-muted-foreground")} />
);

/**
 * The route drawn as reported: solid teal where an operator reported travel, dashed where the rest is only
 * planned (the same solid/dashed grammar as Confirmed/Estimated). Position is per leg, never interpolated.
 */
export function JourneyLine({ shipment, stale, size = "compact" }: { shipment: TrackedShipment; stale: boolean; size?: JourneySize }) {
  const j = journeyOf(shipment);
  const pos = j.position;
  const node = size === "compact" ? "size-1.5" : "size-2";
  const status = pos && STATUS[pos.milestone.status].label;
  const where = pos?.milestone.location;
  // Some feeds put the status in the location ("At sea, bound for …"): say it once.
  const reported = where?.toLowerCase().startsWith((status ?? "").toLowerCase()) ? where : [status, where].filter(Boolean).join(", ");
  const ago = pos && formatAgo(hoursBetween(pos.milestone.at));
  const label = [
    ...j.legs.map(({ leg, progress }) => `${MODE_NAME[leg.mode]} ${leg.from.name} to ${leg.to.name}, ${PROGRESS_TEXT[progress]}`),
    j.delivered ? "delivered" : pos ? `last reported: ${reported}, ${ago}` : "no operator report yet",
  ].join("; ");

  return (
    <div className={cn("min-w-0", size === "compact" ? "w-full max-w-56" : "space-y-1.5")}>
      <div role="img" aria-label={label} className="flex items-end">
        {j.legs.map(({ leg, progress }, i) => {
          const Icon = MODE_ICON[leg.mode];
          const here = pos?.legIndex === i ? pos : undefined;
          const last = i === j.legs.length - 1;
          return (
            <div key={leg.id} className="flex min-w-0 flex-1 flex-col items-stretch gap-0.5">
              <Icon className={cn("mx-auto text-muted-foreground", size === "compact" ? "size-3" : "size-3.5")} />
              {/* Fixed at the marker's height, so the line sits at the same level whichever leg carries the marker. */}
              <div className={cn("flex items-center gap-0.5", size === "compact" ? "h-2.5" : "h-3.5")}>
                {i === 0 && <span className={cn("shrink-0 rounded-full bg-foreground", node)} />}
                {here?.at === "start" && <JourneyMarker status={here.milestone.status} stale={stale} size={size} />}
                <Stretch solid={progress === "done" || (here !== undefined && here.at !== "start")} />
                {here?.at === "middle" && (
                  <>
                    <JourneyMarker status={here.milestone.status} stale={stale} size={size} />
                    <Stretch solid={false} />
                  </>
                )}
                {here?.at === "end" ? (
                  <JourneyMarker status={here.milestone.status} stale={stale} size={size} />
                ) : last ? (
                  <span
                    className={cn(
                      "shrink-0 rounded-[2px] border-2",
                      node,
                      j.delivered ? "border-route bg-route" : "border-foreground bg-card",
                    )}
                  />
                ) : (
                  <span className={cn("shrink-0 rounded-full border-2 border-foreground bg-card", node)} />
                )}
              </div>
              {size === "full" && (
                <div className="flex justify-between gap-2 text-xs text-muted-foreground">
                  <span className="truncate">{i === 0 && leg.from.name}</span>
                  <span className="truncate text-right">{leg.to.name}</span>
                </div>
              )}
            </div>
          );
        })}
      </div>
      {size === "card" && (
        <div className="flex justify-between gap-2 text-xs text-muted-foreground">
          <span className="truncate">{j.legs[0].leg.from.name}</span>
          <span className="truncate text-right">{j.legs.at(-1)!.leg.to.name}</span>
        </div>
      )}
      {size === "card" && pos && (
        <p className="text-sm">
          <span className="text-muted-foreground">Last reported: </span>
          {reported} <span className="text-muted-foreground">· {ago}</span>
        </p>
      )}
    </div>
  );
}

export const ACTION_ICON: Record<NextAction["kind"], LucideIcon> = {
  notify_customer: Mail,
  contact_operator: PhoneCall,
  upload_document: Upload,
  none: CircleCheck,
};

const ACTION_BUTTON: Record<NextAction["kind"], { cta: string; pending: string; done: string }> = {
  notify_customer: { cta: "Send notice", pending: "Sending…", done: "Notice sent" },
  contact_operator: { cta: "Send request", pending: "Sending…", done: "Request sent" },
  upload_document: { cta: "Upload", pending: "Uploading…", done: "Uploaded" },
  none: { cta: "", pending: "", done: "" },
};

/** One click to carry out the proposed action, or proof that it was done. Demo: nothing leaves the app. */
export function ActionControl({
  shipmentId,
  action,
  done,
  compact = false,
}: {
  shipmentId: string;
  action: NextAction;
  done: boolean;
  compact?: boolean;
}) {
  if (action.kind === "none") return null;
  const b = ACTION_BUTTON[action.kind];
  if (done) {
    return (
      <Pill tone="green" title="Demo: recorded here, nothing is sent outside the app">
        <CircleCheck /> {b.done}
      </Pill>
    );
  }
  return (
    <form action={completeAction}>
      <input type="hidden" name="shipmentId" value={shipmentId} />
      <input type="hidden" name="kind" value={action.kind} />
      <SubmitButton
        pendingText={b.pending}
        className={cn("bg-primary text-primary-foreground hover:bg-primary/90", compact && "h-7 px-2 text-xs")}
      >
        {b.cta}
      </SubmitButton>
    </form>
  );
}
